// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQch9osBAbjW7X20ADT-y7neYmNai8gUs',
    appId: '1:950583360069:web:d9949739f69355d6a6c12c',
    messagingSenderId: '950583360069',
    projectId: 'personnaldepense',
    authDomain: 'personnaldepense.firebaseapp.com',
    storageBucket: 'personnaldepense.firebasestorage.app',
    measurementId: 'G-DB9F995H7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_XQsosNMYidceejQAs7HppiglVT4b72g',
    appId: '1:950583360069:android:642452bd4531bdaaa6c12c',
    messagingSenderId: '950583360069',
    projectId: 'personnaldepense',
    storageBucket: 'personnaldepense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtd30BC6X_BO7LEjBPymn1TaIpy8nc-bE',
    appId: '1:950583360069:ios:483f856f4d454237a6c12c',
    messagingSenderId: '950583360069',
    projectId: 'personnaldepense',
    storageBucket: 'personnaldepense.firebasestorage.app',
    iosClientId: '950583360069-i71fekfaqsb50rrtgneuohk7eap538l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalexpensesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtd30BC6X_BO7LEjBPymn1TaIpy8nc-bE',
    appId: '1:950583360069:ios:483f856f4d454237a6c12c',
    messagingSenderId: '950583360069',
    projectId: 'personnaldepense',
    storageBucket: 'personnaldepense.firebasestorage.app',
    iosClientId: '950583360069-i71fekfaqsb50rrtgneuohk7eap538l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalexpensesapp',
  );

}